name: tests

on:
  push:
    branches:    
      - '**'  # matches every branch
jobs:
  tests:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
        
        - name: Install dependencies
          run: npm i

        - name: Downgrade doctoc version
          run: |
            npm install -g doctoc@2.1.0
        
        - name: Start integration test
          env: 
            TEST_REPO: ${{ secrets.TEST_REPO }}
            TEST_BRANCH: ${{ secrets.TEST_BRANCH }}
            TEST_ACCESSTOKEN: ${{ secrets.TEST_ACCESSTOKEN }}
          run: |
            python3 -m unittest action_test.py
            npm test
  
        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ github.token }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  module-dependencies-license-checker:
      needs: tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: |
            sudo npm install -g license-checker
            npm i

        - name: Get all dependent module licenses
          run: |
            license-checker --summary
            license-checker --csv --out ./module-dependencies-license-report.csv

        - name: Upload module-dependencies license report to Artifact
          uses: actions/upload-artifact@v2
          with:
            name: module-dependencies-license-report
            path: ${{ github.workspace }}/module-dependencies-license-report.csv

  scan-for-vulnerabilities:
      needs: module-dependencies-license-checker
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        - name: Install dependencies
          run: |
            npm i
            sudo npm install -g npm-audit-html
        
        - name: Scan for vulnerabilities and report them in a html file
          run: npm audit --json | npm-audit-html --output vulnerabilities-audit-report.html

        - name: Upload vulnerabilities report to Artifact
          uses: actions/upload-artifact@v2
          with:
            name: vulnerabilities-audit-report
            path: ${{ github.workspace }}/vulnerabilities-audit-report.html

  size-of-dependencies-stats:
      needs: scan-for-vulnerabilities
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        - name: Install dependencies
          run: |
            sudo npm install -g cost-of-modules
            npm i

        - name: Get size of dependencies
          run: cost-of-modules | tee size-of-dependencies.log

        - name: Upload size of dependencies stats to Artifact
          uses: actions/upload-artifact@v2
          with:
            name: size-of-dependencies
            path: ${{ github.workspace }}/size-of-dependencies.log
  
  update_release_version:
      needs: size-of-dependencies-stats
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Update release and bump package version
          run: |
            sudo pip3 install ruamel.yaml
            sudo python3 update_release_version.py
            npm --no-git-tag-version version patch
            git config user.name dineshsonachalam
            git config user.email dineshsonachalam@gmail.com
            git pull origin '${{ github.ref }}'
            git add docs/latest-release.yml docs/markdown-autodocs.yml package.json
            git commit -m "Updated release version in YAML docs" docs/latest-release.yml docs/markdown-autodocs.yml package.json
            git push origin '${{ github.ref }}'

  deploy:
      needs: update_release_version
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master'
      steps:
        - uses: actions/checkout@v2
                
        - uses: JS-DevTools/npm-publish@v1
          with:
            token:  ${{ secrets.NPM_ACCESS_TOKEN }}
